name: Module 1 Adaptive CI

# https://github.com/github/view_component/actions/runs/1539034766/workflow

on:
  pull_request:
    paths:
      - 'src/**'
    branches: [ main ]

jobs:

  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      updated_modules: ${{ steps.changes.outputs.updated_modules}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        run: |
          UPDATED_FILES=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)
          echo "::set-output name=updated_modules::$UPDATED_FILES"

  allFiles:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.updated_modules}}
    steps:
      - name: echo changed ALL files
        run: |
          for file in ${{ needs.changedfiles.outputs.updated_modules }}; do
            echo "$file was changed"
          done

  module1CI:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{"src/module-1" in needs.changedfiles.outputs.updated_modules}}
    steps:
      - name: echo Module 1 CI started

  module2CI:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{"src/module-2" in needs.changedfiles.outputs.updated_modules}}
    steps:
      - name: echo Module 2 CI started

  module3CI:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{"src/module-3" in needs.changedfiles.outputs.updated_modules}}
    steps:
      - name: echo Module 3 CI started
