name: Module 1 Adaptive CI

on:
  push:
    paths:
      - 'src/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'
    branches: [ main ]

jobs:

  changedfiles:
    runs-on: ubuntu-latest
    outputs:
#      all: ${{ steps.changes.outputs.all}}
#      js: ${{ steps.changes.outputs.js }}
      updated_modules: ${{ steps.changes.outputs.updated_modules}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        run: |
          UPDATED_FILES=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)
          echo "# 1"
          echo $UPDATED_FILES
          echo "# 2"
          for i in "${UPDATED_FILES[@]}"; do
            echo "$i"
          echo "# 9"
          echo "::set-output name=updated_modules::$UPDATED_FILES"
#          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
#          echo "::set-output name=js::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .js$ | xargs)"

  allFiles:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.updated_modules}}
    steps:
      - name: echo changed ALL files
#        run: echo ${{needs.changedfiles.outputs.updated_modules}}
        run: |
          for file in ${{ needs.changedfiles.outputs.updated_modules }}; do
            echo "$file was changed"
          done
