name: Module 1 Adaptive CI

on:
  push:
    paths:
      - 'src/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print uname
        run: uname -a

  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      js: ${{ steps.changes.outputs.js }}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=js::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .js$ | xargs)"

  jsFiles:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.js}}
    steps:
      - name: echo changed JS files
#        run: echo ${{needs.changedfiles.outputs.js}}
        run: |
          for file in ${{ needs.changedfiles.outputs.js }}; do
            echo "$file was changed"
          done        

  allFiles:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.all}}
    steps:
      - name: echo changed ALL files
#        run: echo ${{needs.changedfiles.outputs.all}}
        run: |
          for file in ${{ needs.changedfiles.outputs.all }}; do
            echo "$file was changed"
          done
