name: Child workflow

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "Parent workflow" ]
    type:
      - complete

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "Hi, I'm a child workflow."
