name: Child workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Default child message [workflow_dispatch]'
        required: false

  workflow_call:
    inputs:
      message:
        description: 'Default child message [workflow_call]'
        required: false
        type: string

jobs:
  execute:
    runs-on: ubuntu-latest

    env:
      MESSAGE: ${{ github.event.inputs.message }}
      MESSAGE_FROM_PARENT: ${{ inputs.message }}

    steps:
      - name: print message
        run: |
          echo "Hi, I'm a child workflow. Message is ${{ env.MESSAGE || env.MESSAGE_FROM_PARENT }}"
          echo "env.MESSAGE is ${{ env.MESSAGE }}" |
          echo "env.MESSAGE_FROM_PARENT is ${{ env.MESSAGE_FROM_PARENT }}"
