name: Module 2 Adaptive CI

on:
  push:
    paths:
      - 'src/module-2/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print uname
        run: uname -a
