name: Module 1 Adaptive CI

on:
  push:
    paths:
      - 'src/module-1/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print uname
        run: uname -a
