name: Parent workflow

on:
  workflow_dispatch:

  # https://jasonet.co/posts/scheduled-actions/
  schedule:
    # Every Monday at 12PM UTC
    - cron: "0 12 * * 1"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "[$(date +"%r")] Hi, I'm a parent workflow."
  call-workflow:
    uses: h3xxx/github-actions-sandbox/.github/workflows/child.yml@main
  call-workflow-passing-data:
    uses: h3xxx/github-actions-sandbox/.github/workflows/child.yml@main
    with:
      message: Parent message [call-workflow-passing-data]
