name: Parent parallel workflow

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "[$(date +"%r")] Hi, I'm a parent parallel workflow."
  call-workflow-1-passing-data:
    uses: h3xxx/github-actions-sandbox/.github/workflows/child-1.yml@main
    with:
      message: Parent message 1 [call-workflow-passing-data]
  call-workflow-2-passing-data:
    uses: h3xxx/github-actions-sandbox/.github/workflows/child-2.yml@main
    with:
      message: Parent message 2 [call-workflow-passing-data]
  call-workflow-2-required-params-passing-data:
    uses: h3xxx/github-actions-sandbox/.github/workflows/child-2-required-params.yml@main
    with:
      message: Parent message 3 [call-workflow-passing-data]
  call-workflow-with-secret:
    uses: h3xxx/github-actions-sandbox/.github/workflows/workflow-with-secret.yml@main
    with:
      message: Parent message 4 [call-workflow-passing-data]
