# Test workflow

name: Test workflow

on:
  workflow_dispatch:
    inputs:
      output_value:
        description: 'Output value:'
        required: true
        default: 'country'
      test_value:
        description: 'Test value:'
        required: true
        default: 'new usa'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OUTPUT_VALUE: ${{ github.event.inputs.output_value }}
      TEST_VALUE: ${{ github.event.inputs.test_value }}

    steps:
      - name: Install jq
        run: |
          sudo apt-get install jq -y
      - name: Process response
        run: |
          TEST_VALUE=$(echo "$TEST_VALUE" | sed "s/usa/uk/")
          TEST_VALUE=$(echo "$TEST_VALUE" | sed "s/ /%20/")
          echo "testValue: $TEST_VALUE"
          curl -s -X GET "https://api.myip.com" -H  "accept: */*" | jq -r .${{ env.OUTPUT_VALUE }}
