# Test workflow

name: Test workflow

on:
  workflow_dispatch:
    inputs:
      output_value:
        description: 'Output value:'
        required: true
        default: 'country'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OUTPUT_VALUE: ${{ github.event.inputs.output_value }}

    steps:
      - name: Install jq
        run: |
          sudo apt-get install jq -y
      - name: Process response
        run: |
          echo "step 1"
          echo "$OUTPUT_VALUE"
          echo "${{ env.OUTPUT_VALUE }}"
          cat $GITHUB_ENV
          OUTPUT_VALUE=$(echo "$OUTPUT_VALUE" | sed "s/usa/uk/")
          OUTPUT_VALUE=$(echo "$OUTPUT_VALUE" | sed "s/ /%20/")
          echo "step 2"
          echo "$OUTPUT_VALUE"
          echo "${{ env.OUTPUT_VALUE }}"
          cat $GITHUB_ENV
          curl -s -X GET "https://api.myip.com" -H  "accept: */*" | jq -r ".$OUTPUT_VALUE"
