name: Workflow with secret

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'message'
        required: false
        default: 'Workflow with secret message [workflow_dispatch]'

  workflow_call:
    inputs:
      message:
        description: 'Workflow with secret message [workflow_call]'
        required: false
        type: string

jobs:
  execute:
    runs-on: ubuntu-latest

    env:
      MESSAGE: ${{ github.event.inputs.message || inputs.message }}

    steps:
      - name: print message
        run: |
          echo "Hi, I'm a Workflow with secret. Message is ${{ env.MESSAGE }}"
          echo "Secret is: ${{ secrets.SOME_SECRET }}"
          if [[ "1234567890" == "${{ secrets.SOME_SECRET }}" ]] ;then echo MATCH! ;fi
