name: Workflow with secret

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'message'
        required: false
        default: 'Workflow with secret message [workflow_dispatch]'

  workflow_call:
    inputs:
      message:
        description: 'Workflow with secret message [workflow_call]'
        required: false
        type: string
    secrets:
      SOME_SECRET_1:
        description: 'Some secret 1'
        required: true

jobs:
  execute:
    runs-on: ubuntu-latest

    env:
      MESSAGE: ${{ github.event.inputs.message || inputs.message }}

    steps:
      - name: print message
        run: |
          echo "Hi, I'm a Workflow with secret. Message is ${{ env.MESSAGE }}"
          echo "Secret is: ${{ secrets.SOME_SECRET }}"
          echo "Secret 1 is: ${{ secrets.SOME_SECRET_1 }}"
          if [[ "1234567890" == "${{ secrets.SOME_SECRET }}" ]] ;then echo Secret MATCH! ;fi
          if [[ "0987654321" == "${{ secrets.SOME_SECRET_1 }}" ]] ;then echo Secret 1 MATCH! ;fi
